### ISSUE TITLE
I can't download your images

### ISSUE THREAD

**Issue by XSLXANDY** [trougnouf/mthesis-denoise#1]
![image](https://user-images.githubusercontent.com/29296287/58847693-749b1080-86b6-11e9-915e-e3e4be5caece.png)
![image](https://user-images.githubusercontent.com/29296287/58848188-3a327300-86b8-11e9-8b2f-eb479b5fc016.png)

I just run dl_ds_1.py. But it seems all the images are stored  as folders rather than jpg.

**Comment by trougnouf** [comment]
Thank you for pointing this out! I was able to replicate the problem, the Wikimedia server is throwing a too many requests error (I added a helpful message). It appears to work using wget, so I would recommend using the --use_wget option if you have access to it (or the newly added --custom_program <dl_program_name>) until I find a native alternative way.

**Comment by XSLXANDY** [comment]
> Thank you for pointing this out! I was able to replicate the problem, the Wikimedia server is throwing a too many requests error (I added a helpful message). It appears to work using wget, so I would recommend using the --use_wget option if you have access to it (or the newly added --custom_program <dl_program_name>) until I find a native alternative way.

Thank you, it works.

**Comment by XSLXANDY** [comment]
> Thank you for pointing this out! I was able to replicate the problem, the Wikimedia server is throwing a too many requests error (I added a helpful message). It appears to work using wget, so I would recommend using the --use_wget option if you have access to it (or the newly added --custom_program <dl_program_name>) until I find a native alternative way.

Thank you, it works.
