### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by titsitits** [trougnouf/mthesis-denoise#2]
Hi, (salut)

I was wondering if you planeed to release this repo (including the trained models) under an open source license (such as MIT or Apache-2.0 for instance) ?

I am working on the development of a toolkit for image restoration and your method for denoising seems interesting (mainly due to the real noisy data user for training I guess). Besides it is a belgian/walloon work so let's be a bit chauvinistic ;) ). You can find my repository here for info: 
https://github.com/titsitits/open-image-restoration
I am very disappointed of the current denoising method (NLRN) so far, it is very slow and generate numerous glitches that worsen the image further after colorization and super-resolution. Your method seems much lighter and more effective. 

However, without an open source license I cannot integrate your work in my toolkit.

Besides, it's seems to be quite an outstanding master thesis you did here (as confirmed by the CVPR output, congrats for that), are you pursuing your research at UCLouvain or elsewhere ?

Mickaël Tits (CETIC asbl)

**Comment by trougnouf** [comment]
Hi Mickaël,
Would you be able to work with the (L)GPL license?
Thank you! I'm starting a PhD with intoPIX and UCLouvain. We are still working on some of the administrative bits but it should be official soon :)
I look forward to your work.
Best,
Benoit
